---
apiVersion: v1
kind: Service
metadata:
  name: booking
  labels:
    run: booking
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
      name: http
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: prometheus
  selector:
    app: booking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
  labels:
    app: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: berwoutv/booking:berwout
          ports:
            - containerPort: 8080
        - name: booking-envoy
          image: berwoutv/booking-envoy:berwout
          ports:
            - containerPort: 80
            - containerPort: 8001