version: '3'
services:
    hotel:
      build:
        context: build/hotel
      image: berwoutv/hotel:berwout

    booking:
      build:
        context: build/booking
      image: berwoutv/booking:berwout

    hotel-envoy:
      build:
        context:
          build/hotel-envoy
      image: berwoutv/hotel-envoy:berwout

    booking-envoy:
      build:
        context:
          build/booking-envoy
      image: berwoutv/booking-envoy:berwout

    front-envoy:
      build:
        context:
          build/front-envoy
      image: berwoutv/front-envoy:berwout
